package ai.ecma.academic.entity.enums;

public enum  NotificationTitle {

    STUDENT_SEND_QUESTION_TO_MENTOR,
    MENTOR__SEND_ANSWER_TO_STUDENT,
    STUDENT_SEND_TASK_TO_TEACHER,
    MENTOR_SEND_ANSWER_TO_STUDENT_TASK,
    TASK_COMPLETE,
    TASK_IGNORED,
    OPENED_LESSON_FOR_STUDENT,
    EVENT_CREATED ,
    EVENT ,
    PASSIVE_USER ,
    FILTERED ,
    EVENT_ACTIVATED_TO_ADMIN,
    AFTER_REGISTERING_EVENT,
    TO_EVENT_SUBSCRIBERS,
    ZOOM_MEETING


}
